---

- name: check connectivity to 8.8.8.8
  hosts: ios_devices
    
  tasks:
    ios_command:
        ansible_connection: network_cli
        ansible_become: yes
        ansible_become_method: enable
        ansible_network_os: ios
        ansible_user: TACACS-NET
        ansible_ssh_pass: TACACS-NET        
      commands: ping 8.8.8.8        
        wait_for:
        - result[0] contains "!!!"
      register: result
      failed_when: "not '!!!' in result.stdout[0]"
